### ISSUE TITLE
security: protect against fork bombs

### ISSUE THREAD

**Issue by theaog** [hackerschoice/segfault#18]
find a way to prevent fork bombs, one idea could be having a script regularly checking user launched processes and renice them or kill them when too many childs are being created.

read https://en.wikipedia.org/wiki/Fork_bomb

> Preventing fork bombs is done by limiting the maximum number of processes a user can own. This is accomplished by: Using the Unix/Linux ulimit parameter to cap the number of processes a user can create. For example, ulimit=30 limits a user to owning 30 processes.

**Comment by d1gg0r** [comment]
Normally yes, in this case not really applicable as we got a root user on the instance who can change and/or adjust the value. However, this can be set as an option for docker itself, e.g.

`sudo docker run -it --pids-limit 32 ...`

**Comment by d1gg0r** [comment]
Also, we might also set plain ulimit values to docker itself, either by 

`docker run --ulimit nofile=<softlimit>:<hardlimit>`

or by maybe setting limits on the bare metal system itself for the docker process(es)

**Comment by DeadPackets** [comment]
You can see that ulimits are already being implemented in https://github.com/hackerschoice/segfault/blob/fa3dc395941cbf3efab03346b0655f3f08b61dbf/host/fs-root/bin/segfaultsh#L383-L421 and also here. https://github.com/hackerschoice/segfault/blob/fa3dc395941cbf3efab03346b0655f3f08b61dbf/host/fs-root/bin/segfaultsh#L702-L708

The main issue seems to be using all the IO to prevent anyone else's container from running. We're trying to prevent this in #17

**Comment by theaog** [comment]
#33

**Comment by theaog** [comment]
@all please review/try ContainerGuard pull request #33, which should close this issue.
