### ISSUE TITLE
help needed: don't let docker crash

### ISSUE THREAD

**Issue by theaog** [hackerschoice/segfault#19]
How can we stop docker from exiting when /var/lib/docker (or in this case /sf/docker) gets full? e.g. how to allow host’s root (not in cgroup) the last 5% of the file system?

**Comment by DeadPackets** [comment]
This could be applicable: https://stackoverflow.com/questions/72926872/how-to-set-the-maximum-storage-space-allowed-in-a-docker-containers-writable-la

**Comment by SkyperTHC** [comment]
neither of those solutions helps. We are already doing this (restricting the root-fs space per container) but the caveat is that a user can create an unlimited amount of new containers and the FS limit can only be set PER container.

Setting the FS limit for 'all of docker' (like with XFS quota or 5% reserver as mount option) causes docker to crash badly when that limit is reached.

The best alternative we have atm is to constantly monitor /var/lib/docker/overlay2 and if it approaches <10% of spare space then we start killing 'large' docker containers from the user........ hmm. what a mess.
