### ISSUE TITLE
feature: ssh payment gateway

### ISSUE THREAD

**Issue by theaog** [hackerschoice/segfault#20]
# SSHPay is a Payment Gateway interfaced through an SSH session

## Why?
> Because it has never been done, and we need it for segfault.net which offers disposable root servers;  we thought it would be cool to offer payment via SSH for Premium features of an SSH service.

## How?
> We're still thinking about the design, though I'll outline the starting point.

I would like to run a customized SSH server written in Go by forking the [stdlib SSH package](https://pkg.go.dev/golang.org/x/crypto/ssh) which gives us a reliable implementation of the ssh server RFC spec: https://datatracker.ietf.org/doc/html/rfc4253

We will modify this ssh server implementation to just present an interactive TUI (Terminal UI) to whomever connects and offer selections for donations, premium features etc, also select-able payment methods and payment flows.

## Example: Connection
```bash
$ ssh pay@segfault.net

Welcome to Segfault's disposable ROOT servers

I want to:
- Donate ($any)
- Standard Segfault.net account ($1)
- Premium Segfault.net account ($100)

using:
- Monero (XMR)
- Bitcoin (BTC)
- PayPal (USD,EUR)
- Stripe (USD)

If you encounter any issues w/ your payment, please open a GitHub issue using the 'payment' template.
```

## Example: Payment flow (XMR)
```bash
You want 'Premium account' and transfer 'Monero (XMR)'

Send 0.1 XMR ($100) to this address (CmtcooNtKp3sba9tGEpprM5PvADwXk76B)
[1m30s] Waiting for transaction...

Transaction successful, thank you!
Your segfault account (fluffy-monster) is ready for action.

$ ssh -o "SetEnv SECRET=bzKQhwnmabcSdcTdWyfuKeIk" \
    fluffy-monster@de.segfault.net

Connection to segfault.net closed.
```

**Comment by DeadPackets** [comment]
I want to add to this that we should support setting environment variables to "automatically" select options on the menu (in case anyone wants to automate buying a segfault box).

I can imagine it working something like `ssh -o "SetEnv SECRET=something SG_PAY_METHOD=monero SG_PAY_REASON=premium"`.

Could love to hear some feedback about this, but was just imagining this being used in automated offensive tooling and it would need a nice way to interact with scripts.

**Comment by SkyperTHC** [comment]
We are moving to a CURL/NGINX API for the user for other service. It makes sense to also have the payment gateway via the same interface.

example (from the root server):
```
curl http://1/upgrade
```

to retrieve a a unique Crypto Address (and ascii QR code?) for the user to pay. A backend server then monitors when the payment arrives (and increases the limits for the user).

A Database is required to track date/time/amount of payment. Payment should be subscription based. Annual or monthly.

The backend server also removes the benefits if the subscription expires.

The same call also returns an AUTH-TOKEN (32 base56 string). The auth-token can then be used to upgrade any other root server as well. A user should be allowed to upgrade up to 2 (?) root servers at the same time. The last two servers where the API is called should get the benefit of the upgrade and any previously upgraded server should loose the benefit.
