### ISSUE TITLE
debconf: delaying package configuration, since apt-utils is not installed

### ISSUE THREAD

**Issue by scriptzteam** [hackerschoice/segfault#38]
Hi :)
another possible error? this getting in log install after command **make** is run.

**lsb_release -a**
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

```debconf: delaying package configuration, since apt-utils is not installed```

**apt install apt-utils**
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
apt-utils is already the newest version (2.4.8).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

**Comment by SkyperTHC** [comment]
I believe this bug is not relevant to SSC. The error comes from the underlaying host (not segfault or the user's root shell). Otherwise please open the issue again or catch me on telegram.
