### ISSUE TITLE
No BFQ-Scheduler - installation

### ISSUE THREAD

**Issue by scriptzteam** [hackerschoice/segfault#56]
This helped me, maybe someone would have need it too :) 
It is due to the update made here - https://github.com/hackerschoice/segfault/blob/19ba707cb35804d5bfd63bfab2aa83ab9ddf78de/sfbin/sf#L95

```
nano /etc/default/grub
add scsi_mod.use_blk_mq=1, so this line looks like:
GRUB_CMDLINE_LINUX="scsi_mod.use_blk_mq=1"

sudo update-grub
reboot -h now
sudo modprobe bfq
```

You can also try this one:
https://github.com/hackerschoice/segfault/blob/19ba707cb35804d5bfd63bfab2aa83ab9ddf78de/sfbin/sf#L94

**Comment by SkyperTHC** [comment]
thanks for reporting.  For me it works without the grub line and just loading the BFQ module. 0.3.7a should now work and not depend on aws anymore.
