### ISSUE TITLE
/everyone -> Directory '.' is not writable

### ISSUE THREAD

**Issue by scriptzteam** [hackerschoice/segfault#60]
```
cd /everyone
nano test.txt

result =>  [ Directory '.' is not writable ]
```

also dir structure has weird folder "this" created?
```
┌──(root💀sf-VillageDrum)-[/everyone]
└─# ls -altr /everyone
total 16
drwxr-xr-x 2 root root 4096 Nov 18 13:51 VillageDrum
drwxr-xr-x 2 root root 4096 Nov 18 13:51 this
drwxr-xr-x 4 root root 4096 Nov 18 13:51 .
drwxr-xr-x 1 root root 4096 Nov 18 13:51 ..
```

**Comment by SkyperTHC** [comment]
correct. This has changed now. Every root shell can write to /everyone/this and that data is then mirrored in /everyone/$SF_HOSTNAME

This means your own data can only be READ (but not deleted or modified) by others (and equally that you can not delete or modify the data of others).

There was to much abuse for people modifying the data of other people.

I shall update the documentation. Thank you for pointing this out.
