### ISSUE TITLE
Web server

### ISSUE THREAD

**Issue by SkyperTHC** [hackerschoice/segfault#66]
Offer web server functionality with automated SSL cert.

- likely best to use a separate domain (not segfault.net).
- need inbound 80/443 that's not the shell server
- allow user to run their own nginx rather than just static webpages (?) or best to run 1 nginx with individual fcgi breakouts. This would make it easy to host static webpages and PHP etc via fcgi breakouts per root server.
- which domain? And best to use domain/ServerName/* for location 

Considerations:
1. Users hosting crap shall not result in problem for segfault (separation of shell server? Force email registration to allow this feature?
2. How to deal with abuse (must make sure that site is not abused for hosting illegal content). How does GitHub.io deal with abuse?
3. Must prevent an attacker to use illegal content as a weapon to shut down segfault (attacker hosts child porn on his root server against our policy. Attack calls fedz to shut us down).

Misc:
1. Localhost.run
2. Argo tunnels (cloudflared)
3. WG forward from BTC VPS
4. Tor2Web?

**Comment by Jiab77** [comment]
From what I've tested, Localhost.run can handle the automated TLS certificate part as it does it by default so basically the web server just needs to listen on port 80 or any other ones as long as it is passed to the SSH tunnel.

The websites can also be hosted under another domain than segfault.net but it's not free but quite cheap.

**Comment by SkyperTHC** [comment]
The user can get his own tunnel. #67
