### ISSUE TITLE
FAQ addition how to run a web server

### ISSUE THREAD

**Issue by SkyperTHC** [hackerschoice/segfault#67]
Ngrok or cloudflared tunnel and how to start nginx.

**Comment by Jiab77** [comment]
[LHR](https://localhost.run/) might be cheaper than Ngrok. Their prices just increased a lot.

I've made a working prototype with LHR and a `PHP` file serving as minimal web server and it worked quite nicely but maybe a little bit slower than with Ngrok.

**Comment by SkyperTHC** [comment]
Done.
