### ISSUE TITLE
Documentation should list prerequisites for installation

### ISSUE THREAD

**Issue by p4tpr0** [hackerschoice/segfault#83]
Hello,

I've spent quite some time trying to install my own SSC on Rocky Linux 9, but it failed hard.
Then I've switched to Ubuntu 22.04 and got some errors: I had to install some prerequisites like docker-compose and make. Even with those installed, the make process eventually fails with:

`E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
The command '/bin/sh -c /pkg-install.sh NET bin https://github.com/hackerschoice/binary/raw/main/gsocket/latest/gsocket_latest_all.deb 	&& /pkg-install.sh NET bash -c '{ apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv-keys B5A08F01796E7F521861B449372D1FF271F2DD50 		&& echo "deb http://deb.ooni.org/ unstable main" | tee /etc/apt/sources.list.d/ooniprobe.list 		&& apt-get update 		&& apt-get install ooniprobe-cli 		&& rm /etc/apt/sources.list.d/ooniprobe.list 		&& apt-get update; }' 	&& /pkg-install.sh NET ghbin shadowsocks/shadowsocks-rust 'x86_64.*linux.musl.tar.xz$' 	&& /pkg-install.sh NET ghbin KaranGauswami/socks-to-http-proxy 'sthp-linux' sthp 	&& /pkg-install.sh NET ghbin schollz/croc 'Linux-64bit.deb' 	&& /pkg-install.sh NET apt-get install -y --no-install-recommends 		tinyproxy' returned a non-zero code: 255
make[1]: *** [Makefile:2: all] Error 255
make[1]: Leaving directory '/home/patpro/segfault/guest'
make: *** [Makefile:11: all] Error 2
`

I've added manually gnupg, gnupg2, gsocket and I've got the same result.

What are the proper prerequisites for a working installation of a segfault.net SSC? (distrib, version, preinstalled pkg, etc.)

Thanks a lot!

**Comment by SkyperTHC** [comment]
Hi,

sorry for not being up to date with the documentation. I just pushed 0.4.5b2 to main. Try that one.

Best source is https://github.com/hackerschoice/segfault/wiki/Bare-Metal-Deployment. That's how we deploy it.

Catch me on TG and I can give you a helping hand or we can do it together. 

Thanks for sharing your feedback.
