### ISSUE TITLE
Support for ARM (feature)

### ISSUE THREAD

**Issue by p4tpr0** [hackerschoice/segfault#85]
Hi,
Trying to install on Ubuntu 22.04 arm64 (aarch64) fails with this error: 

`dpkg: error processing archive /tmp/pkg.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 /tmp/pkg.deb
The command '/bin/sh -c /pkg-install.sh NET bin https://github.com/hackerschoice/binary/raw/main/gsocket/latest/gsocket_latest_all.deb 	&& /pkg-install.sh NET ghbin shadowsocks/shadowsocks-rust 'x86_64.*linux.musl.tar.xz$' 	&& /pkg-install.sh NET ghbin ginuerzh/gost  'linux-amd64.*gz$' gost 	&& /pkg-install.sh NET ghbin KaranGauswami/socks-to-http-proxy 'sthp-linux' sthp 	&& /pkg-install.sh NET ghbin schollz/croc 'Linux-64bit.deb' 	&& /pkg-install.sh NET ghbin vi/websocat 'x86_64.*linux' websocat 	&& /pkg-install.sh NET ghbin ViRb3/wgcf  'linux_amd64$' wgcf 	&& /pkg-install.sh NET apt-get install -y --no-install-recommends 		microsocks 		tinyproxy' returned a non-zero code: 1
make[1]: *** [Makefile:2: all] Error 1
make[1]: Leaving directory '/home/patpro/segfault/guest'
make: *** [Makefile:11: all] Error 2
`

ARM CPU are becoming more prevalent, that would be nice to support arm64 arch.

**Comment by SkyperTHC** [comment]
Hello,

The latest on GitHub (0.4.5b3) now supports aarch64. It's not widely used for Desktop or workstations and thus some tools and apps had to be excluded (like firefox etc). I marked the excluded ones with `# x86_64 only` in the guest/Dockerfile.

This version builds fine for me on an AWS aarch64/Ubuntu t4g.micro instance.

Thank you for reporting this. Please test and feel free to re-open the issue if the problem persists.
